name: Build and Push Docker Image
    2 
    3 on:
    4   push:
    5     branches: [ main ]
    6   pull_request:
    7     branches: [ main ]
    8 
    9 jobs:
   10   build:
   11     runs-on: ubuntu-latest
   12     permissions:
   13       contents: read
   14       packages: write
   15 
   16     steps:
   17     - name: Checkout repository
   18       uses: actions/checkout@v4
   19 
   20     - name: Set up Docker Buildx
   21       uses: docker/setup-buildx-action@v3
   22 
   23     - name: Log in to Container Registry
   24       uses: docker/login-action@v3
   25       with:
   26         registry: ghcr.io
   27         username: ${{ github.actor }}
   28         password: ${{ secrets.GITHUB_TOKEN }}
   29 
   30     - name: Extract metadata
   31       id: meta
   32       uses: docker/metadata-action@v5
   33       with:
   34         images: ghcr.io/${{ github.repository }}
   35         tags: |
   36           type=ref,event=branch
   37           type=ref,event=pr
   38           type=sha,prefix={{branch}}-
   39           type=raw,value=latest,enable={{is_default_branch}}
   40 
   41     - name: Build and push Docker image
   42       uses: docker/build-push-action@v5
   43       with:
   44         context: .
   45         platforms: linux/amd64,linux/arm64
   46         push: true
   47         tags: ${{ steps.meta.outputs.tags }}
   48         labels: ${{ steps.meta.outputs.labels }}
   49         cache-from: type=gha
   50         cache-to: type=gha,mode=max
